use std::pin::Pin;
use tokio::sync::mpsc;
use tokio_stream::{wrappers::ReceiverStream, Stream, StreamExt};
use tonic::{transport::Server, Request, Response, Status, Streaming};

// 1. Mocking the code usually auto-generated by the Protobuf Compiler (protoc)
pub mod fleet_routing {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct DriverLocation {
        #[prost(string, tag = "1")]
        pub driver_id: ::prost::alloc::string::String,
        #[prost(double, tag = "2")]
        pub latitude: f64,
        #[prost(double, tag = "3")]
        pub longitude: f64,
    }

    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct DispatchInstruction {
        #[prost(string, tag = "1")]
        pub instruction_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub action: ::prost::alloc::string::String,
    }
}

use fleet_routing::{DriverLocation, DispatchInstruction};

// 2. Define the gRPC Service Trait
#[tonic::async_trait]
pub trait DispatcherService: Send + Sync + 'static {
    // The complex return type for a Bidirectional Stream
    type RouteFleetStream: Stream<Item = Result<DispatchInstruction, Status>> + Send + 'static;

    async fn route_fleet(
        &self,
        request: Request<Streaming<DriverLocation>>,
    ) -> Result<Response<Self::RouteFleetStream>, Status>;
}

// 3. The Implementation of the Service
#[derive(Debug, Default)]
pub struct PlatformDispatcher {}

#[tonic::async_trait]
impl DispatcherService for PlatformDispatcher {
    // We must Pin the Boxed stream to a specific memory address because it is an asynchronous generator
    type RouteFleetStream = Pin<Box<dyn Stream<Item = Result<DispatchInstruction, Status>> + Send>>;

    async fn route_fleet(
        &self,
        request: Request<Streaming<DriverLocation>>,
    ) -> Result<Response<Self::RouteFleetStream>, Status> {
        
        let mut inbound_stream = request.into_inner();
        
        // Create an asynchronous message channel to push instructions back to the client
        let (tx, rx) = mpsc::channel(128);

        // Spawn a detached Tokio task to handle the incoming stream concurrently
        tokio::spawn(async move {
            while let Some(location_result) = inbound_stream.next().await {
                match location_result {
                    Ok(location) => {
                        println!("Received location from driver {}: {}, {}", 
                                 location.driver_id, location.latitude, location.longitude);

                        // Complex routing algorithm simulation...
                        let instruction = DispatchInstruction {
                            instruction_id: format!("cmd-{}", location.driver_id),
                            action: String::from("PROCEED_TO_SURGE_ZONE"),
                        };

                        // Push the instruction back down the open HTTP/2 TCP socket
                        if let Err(e) = tx.send(Ok(instruction)).await {
                            eprintln!("Client dropped connection: {}", e);
                            break;
                        }
                    }
                    Err(e) => {
                        eprintln!("Error reading from gRPC stream: {}", e);
                        break;
                    }
                }
            }
            println!("gRPC Stream completely terminated.");
        });

        // Wrap the receiving end of our channel into a stream and return it
        let outbound_stream = ReceiverStream::new(rx);
        Ok(Response::new(Box::pin(outbound_stream) as Self::RouteFleetStream))
    }
}
